[phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[phases.install]
cmds = ["cd server && npm install"]

[phases.build]
cmds = ["cd server && npm rebuild better-sqlite3"]

[start]
cmd = "cd server && NODE_ENV=production node index.js"
