[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd client && npm install",
  "cd ../server && npm install --omit=dev"
]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd server && NODE_ENV=production node index.js"
